printWidth = 79
tabWidth = 2
semi = false
singleQuote = true
trailingComma = "none"
arrowParens = "avoid"
bracketSpacing = true
plugins = ["prettier-plugin-astro"]

[[overrides]]
files = "*.astro"
options = { parser = "astro" }
